[project]
name = "pytorch-mnist-pipeline"
version = "0.1.0"
description = "A simple PyTorch pipeline for training a model on the MNIST dataset."
readme = "README.md"
requires-python = ">=3.10,<3.12"
dependencies = [
  "setuptools",
  "torch==2.7.1",
  "torchvision==0.22.1",
  "torchaudio==2.7.1",
  "tensorboard",
  "ipykernel",
  "ipywidgets",
  "IProgress",
  "matplotlib",
  "pandas",
  "scipy",
  "scikit-learn",
  "seaborn",
  "torchmetrics",
  "safetensors>=0.8.0",
]

[[tool.uv.index]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"
explicit = true

[[tool.uv.index]]
url = "https://storage.googleapis.com/tpu-pytorch/wheels/"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu118" }
torchvision = { index = "pytorch-cu118" }
torchaudio = { index = "pytorch-cu118" }
